sudo: required
language: generic
services:
  - docker

before_installed:
  - docker build -t 10001024/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 10001024/docker-react npm run test
